#!/usr/bin/env bash

set -e

# Create variables
export TOOLCHAINS=org.swift.540202104261a
export SWIFT_ANDROID_HOME=$SWIFT_ANDROID_HOME_5_4
export SWIFT_ANDROID_API_LEVEL=24
export ANDROID_NDK=$ANDROID_NDK_ROOT_21E
export ANDROID_NDK_ROOT=$ANDROID_NDK
export ANDROID_NDK_HOME=$ANDROID_NDK

# Update PATH
export PATH=$ANDROID_NDK:$PATH
export PATH=$SWIFT_ANDROID_HOME/bin:$SWIFT_ANDROID_HOME/build-tools/current:$PATH