name: Pull Request Check

on: pull_request

defaults:
  run:
    shell: zsh -l {0} # Use zsh iwth login as default shell

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  Android:
    name: "mailcore2 - Android"
    runs-on: [self-hosted, macOS, ARM64, Android]
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run android tests
      run: ./build-scripts/test-android.sh
    - name: Publish Report
      uses: mikepenz/action-junit-report@v3
      if: failure()
      with:
        report_paths: .build/reports/junit.xml
        check_name: mailcore2-android
        detailed_summary: true
        include_passed: true
        
  macOS:
    name: "mailcore2 - macOS"
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run android tests
      run: ./build-scripts/test-macos.sh
    - name: Publish Report
      uses: mikepenz/action-junit-report@v3
      if: failure()
      with:
        report_paths: .build/reports/junit.xml
        check_name: mailcore2-macOS
        detailed_summary: true
        include_passed: true
        
  iOS:
    name: "mailcore2 - iOS"
    runs-on: [self-hosted, macOS, ARM64, Android]
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run android tests
      run: ./build-scripts/test-ios.sh
    - name: Publish Report
      uses: mikepenz/action-junit-report@v3
      if: failure()
      with:
        report_paths: .build-ios/reports/junit.xml
        check_name: mailcore2-iOS
        detailed_summary: true
        include_passed: true
